tcp_tf_broadcaster:
  ros__parameters:
    input_topic: /jaka_driver/tool_position
    parent_frame: base_link
    child_frame: jaka_tcp
    use_degrees: true

static_camera_tf:
  ros__parameters:
    parent_frame: jaka_tcp
    child_frame: camera_link
    xyz: [0.0, 0.0, 0.0]
    rpy: [0.0, 0.0, 0.0]
    degrees: false

joint_state_relay:
  ros__parameters:
    input_topic: /jaka_driver/joint_position
    output_topic: /joint_states
    clear_frame_id: true
